### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by sirmax1** [Heat-Ledger-Ltd/heatwallet#1]
Seems to be missing the server side for the windows version.
it tries to run "bin\\heatledger.bat" which does not exist..

Full log:
"[SERVER] command >> bin\\heatledger.bat"
"[SERVER] cwd >> Z:\\Apps\\Heatclient\\resources\\heatledger"
"[SERVER] pid >> undefined"
"[SPAWN EXIT] spawn C:\\Windows\\system32\\cmd.exe ENOENT"

**Comment by dmdeklerk** [comment]
should work by now
